name: hw-aws-sqs-conduit
version: '0.1.0.0'
category: Web
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2017 John Ky
license: BSD3
github: githubuser/hw-aws-sqs-conduit
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Aws.Sqs.Conduit
  dependencies:
  - base >=4.7 && <5
  - amazonka
  - amazonka-sqs
  - conduit
  - lens
  - mtl
  - text
tests:
  hw-aws-sqs-conduit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hw-aws-sqs-conduit
